# Generated by Django 6.0.6 on 2026-10-05 01:00

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_creditos', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'paquetes_credito',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_creditos__gt', 0)), name='paquete_cantidad_creditos_positiva'), models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='paquete_precio_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaccion_externa', models.CharField(max_length=255, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_transaccion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], max_length=50)),
                ('fecha', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='billing.creditpackage')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transacciones_pagos',
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='transaccion_monto_positivo'), models.CheckConstraint(condition=models.Q(('estado_transaccion__in', ['pendiente', 'aprobado', 'fallido', 'reembolsado', 'cancelado'])), name='transaccion_estado_valido')],
            },
        ),
    ]
